name: Update README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm update-readme
      # git
      - run: git config user.name jct301
      - run: git config user.email jctr.301@gmail.com
      - run: git add README.md
      - run: git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
      - run: git push origin master