name: Update README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    with:
      node-version: 20
    - run: npm install
    - run: npm run update-readme
    - run: |
    git config user.name midudev
    git config user.email miduga@gmail.com
    git add README.md
    git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
    git push origin master